export default {
    "login": "vlad200dev",
    "id": 51855262,
    "node_id": "MDQ6VXNlcjUxODU1MjYy",
    "avatar_url": "https://avatars.githubusercontent.com/u/51855262?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/vlad200dev",
    "html_url": "https://github.com/vlad200dev",
    "followers_url": "https://api.github.com/users/vlad200dev/followers",
    "following_url": "https://api.github.com/users/vlad200dev/following{/other_user}",
    "gists_url": "https://api.github.com/users/vlad200dev/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/vlad200dev/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/vlad200dev/subscriptions",
    "organizations_url": "https://api.github.com/users/vlad200dev/orgs",
    "repos_url": "https://api.github.com/users/vlad200dev/repos",
    "events_url": "https://api.github.com/users/vlad200dev/events{/privacy}",
    "received_events_url": "https://api.github.com/users/vlad200dev/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Vladislav",
    "company": null,
    "blog": "https://vladnet.pro/",
    "location": null,
    "email": null,
    "hireable": true,
    "bio": "Fullstack developer. Javascript/Java stack",
    "twitter_username": null,
    "public_repos": 86,
    "public_gists": 0,
    "followers": 0,
    "following": 12,
    "created_at": "2019-06-15T13:02:45Z",
    "updated_at": "2023-11-26T15:11:56Z"
};
